import turtle
jacob = turtle.pen
jacob = turtle.Pen()
jacob.left(180)
jacob.forward(80)
kate = turtle.Pen()
kate.left(90)
kate.forward(100)
avery = turtle.Pen()
avery.forward(50)
avery.right(90)
avery.forward(20)
kate = turtle.Pen()
kate.right(90)
kate.forward(100)
